name:                chiphunk
version:             0.1.0.0
synopsis:            Haskell bindings for Chipmunk2D physics engine
description:         See "Chiphunk.Low" for documentation
homepage:            https://github.com/CthulhuDen/chiphunk#readme
license:             BSD3
author:              Cthulhu
maintainer:          cthulhu.den@gmail.com
copyright:           Cthulhu (c) 2018
category:            Physics
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

library:
  source-dirs:       src
  exposed-modules:
  - Chiphunk.Low
  other-modules:
  - Chiphunk.Low.Math
  - Chiphunk.Low.Types
  - Chiphunk.Low.Internal
  - Chiphunk.Low.Helper
  - Chiphunk.Low.Vect
  - Chiphunk.Low.BB
  - Chiphunk.Low.Body
  - Chiphunk.Low.Shape
  - Chiphunk.Low.Space
  - Chiphunk.Low.Constraint
  - Chiphunk.Low.Callback
  - Chiphunk.Low.Arbiter
  include-dirs:
  - Chipmunk2D-7.0.2/include
  - src/Chiphunk
  dependencies:
  - vector-space
  - safe-exceptions
  verbatim:
    c-sources: |
      Chipmunk2D-7.0.2/src/chipmunk.c
      Chipmunk2D-7.0.2/src/cpConstraint.c
      Chipmunk2D-7.0.2/src/cpSpaceStep.c
      Chipmunk2D-7.0.2/src/cpShape.c
      Chipmunk2D-7.0.2/src/cpSpace.c
      Chipmunk2D-7.0.2/src/cpArbiter.c
      Chipmunk2D-7.0.2/src/cpArray.c
      Chipmunk2D-7.0.2/src/cpBBTree.c
      Chipmunk2D-7.0.2/src/cpBody.c
      Chipmunk2D-7.0.2/src/cpCollision.c
      Chipmunk2D-7.0.2/src/cpDampedRotarySpring.c
      Chipmunk2D-7.0.2/src/cpDampedSpring.c
      Chipmunk2D-7.0.2/src/cpGearJoint.c
      Chipmunk2D-7.0.2/src/cpGrooveJoint.c
      Chipmunk2D-7.0.2/src/cpHashSet.c
      Chipmunk2D-7.0.2/src/cpHastySpace.c
      Chipmunk2D-7.0.2/src/cpMarch.c
      Chipmunk2D-7.0.2/src/cpPinJoint.c
      Chipmunk2D-7.0.2/src/cpPivotJoint.c
      Chipmunk2D-7.0.2/src/cpPolyline.c
      Chipmunk2D-7.0.2/src/cpPolyShape.c
      Chipmunk2D-7.0.2/src/cpRatchetJoint.c
      Chipmunk2D-7.0.2/src/cpRobust.c
      Chipmunk2D-7.0.2/src/cpRotaryLimitJoint.c
      Chipmunk2D-7.0.2/src/cpSimpleMotor.c
      Chipmunk2D-7.0.2/src/cpSlideJoint.c
      Chipmunk2D-7.0.2/src/cpSpaceComponent.c
      Chipmunk2D-7.0.2/src/cpSpaceDebug.c
      Chipmunk2D-7.0.2/src/cpSpaceHash.c
      Chipmunk2D-7.0.2/src/cpSpaceQuery.c
      Chipmunk2D-7.0.2/src/cpSpatialIndex.c
      Chipmunk2D-7.0.2/src/cpSweep1D.c

      src/Chiphunk/wrapper.c


executables:
  chiphunk:
    when:
    - condition: flag(library-only)
      buildable: false
    source-dirs:     app
    main:            Main.hs
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - chiphunk
    - gloss
    - async
    - lens
    - containers
    - safe-exceptions
    - GLUT
    - OpenGL

flags:
  library-only:
    manual: false
    default: false
