resolver: lts-12.7

packages:
- .

extra-deps:
- nanovg-0.6.0.0
- git: https://github.com/CthulhuDen/nanovg-simple
  commit: fd293e4f93bf0fa2b065132a5a072a3fbda58d8e

flags:
  chiphunk:
    library-only: false
